### PR TITLE
Fixed issue #92

### PR DESCRIPTION
**Pull request by dmoklaf**
This fixes

https://github.com/danielnsilva/semanticscholar/issues/92

Calling nest_asyncio.apply() from this class is useless as it is already called from the base synchronous master object that controls all the API, SemanticScholar.

Successfully tested in both synchronous and asynchronous modes.

### CODE REVIEW

**Comment by danielnsilva** [comment]
This PR also addresses #93

**Comment by danielnsilva** [comment]
LGTM! Thanks @dmoklaf

**Comment by danielnsilva** [comment]
> PS : for the future I think the PaginatedResults class could be split in 2 sync vs async versions. This would make the API and code much clearer than it is today, exactly like the SemanticScholar class.

It might be worth opening an issue or PR to discuss this further.

**Comment by dmoklaf** [comment]
Hi, is this possible to release a new version with this? Thx

**Pull request merged**
