### PR TITLE
Update restful.py

### PR DESCRIPTION
**Pull request by Summer-94**
try to add support for arxivId

### CODE REVIEW

**Comment by danielnsilva** [comment]
Hi @Summer-94, sorry for the delay in responding. I'm not sure I understand the purpose of this PR. ArXiv ID is already supported. In [Semantic Scholar API](https://api.semanticscholar.org/), except for S2 Paper ID and DOI, other paper identifiers need a prefix. Can you clarify why is it necessary to try to recognize ArXiv ID? Let users set the corresponding prefix is not a better choice? I wonder if `re.match` could affect performance.

**Comment by Summer-94** [comment]
Ah, yes, you are right. I didn't realize that I can add prefix 'arXiv:' before ArXiv Id as a input parameter, my mistake.  
It should works fine now.
Thanks for your reply.

**Comment by Summer-94** [comment]
My problem, there is no need to update the code.

**Comment by danielnsilva** [comment]
> Ah, yes, you are right. I didn't realize that I can add prefix 'arXiv:' before ArXiv Id as a input parameter, my mistake.
> It should works fine now.
> Thanks for your reply.

That's ok. Thank you for your interest in contributing to the project.

**Pull request closed without merging**
